---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: core-validator
  labels:
    role: validation
spec:
  replicas: 1
  strategy: # we should have a rolling update strategy i.e changes deployed automatically
    type: "RollingUpdate"
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: core-validator
    spec:
      containers:
         - name: core-validator
           imagePullPolicy: IfNotPresent
           image: core-validator:latest
           env:
             - name: MONGO_URI
               value: mongodb://${MONGO_SERVICE_SERVICE_HOST}:${MONGO_SERVICE_SERVICE_PORT}
             - name: RABBIT_HOST
               value: ${RABBIT_SERVICE_SERVICE_HOST}
             - name: RABBIT_PORT
               value: ${RABBIT_SERVICE_SERVICE_PORT}
