apiVersion: v1
kind: Service
metadata:
  labels:
    role: submission
  name: mongo-service
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongo
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
