apiVersion: v1
kind: Service
metadata:
  labels:
    role: submission
  name: rabbit-service
spec:
  ports:
    - port: 5672
      protocol: TCP
      targetPort: 5672
  selector:
    app: rabbit
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
