apiVersion: v1
kind: Service
metadata:
  labels:
    role: submission
  name: ingest-api-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ingest-api
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
