matrix:
    include:
        - language: java
          jdk: openjdk8
        - language: python
          python:
              - 2.7
              - 3.6

sudo: required
services:
    - docker

branches:
    only:
        - master
        - develop

before_script:
    - python2.7 -m pip --version || wget https://bootstrap.pypa.io/get-pip.py | python2.7
    - python3 -m pip --version || wget https://bootstrap.pypa.io/get-pip.py | python3

script: python3 -m pip --version

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/