---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingest-core
  namespace: dev-environment
  labels:
    role: ingestion
spec:
  replicas: 1
  strategy: 
    type: "RollingUpdate"
  template: 
    metadata:
      labels:
        app: ingest-core
    spec:
      containers:
         - name: ingest-core
           image: quay.io/humancellatlas/ingest-core
           env:
             - name: MONGO_URI
               value: mongodb://${MONGO_SERVICE_SERVICE_HOST}:${MONGO_SERVICE_SERVICE_PORT}/admin
             - name: RABBIT_HOST
               value: ${RABBIT_SERVICE_SERVICE_HOST}
             - name: RABBIT_PORT
               value: ${RABBIT_SERVICE_SERVICE_PORT_SERVICE}
           ports:
             - containerPort: 8080
