---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingest-demo
  namespace: integration-environment
  labels:
    role: ingestion
spec:
  replicas: 1
  strategy:
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        app: ingest-demo
    spec:
      containers:
         - name: ingest-demo
           imagePullPolicy: Always
           image: quay.io/humancellatlas/ingest-demo
           env:
             - name: INGEST_API
               value: http://api.ingest.integration.data.humancellatlas.org:80
           ports:
             - containerPort: 5000
