---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingest-exporter
  namespace: integration-environment
  labels:
    role: ingestion
spec:
  replicas: 3
  strategy:
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        app: ingest-exporter
    spec:
      containers:
         - name: ingest-exporter
           imagePullPolicy: Always
           image: quay.io/humancellatlas/ingest-exporter:v0.0.4.rc
           env:
             - name: INGEST_API
               value: http://api.ingest.integration.data.humancellatlas.org:80
             - name: RABBIT_URL
               value: amqp://${RABBIT_SERVICE_SERVICE_HOST}:${RABBIT_SERVICE_SERVICE_PORT_SERVICE}
             - name: DSS_API
               value: https://dss.staging.data.humancellatlas.org
             - name: STAGING_API
               value: https://upload.staging.data.humancellatlas.org
             - name: INGEST_API_KEY
               valueFrom:
                 secretKeyRef:
                   name: api-keys
                   key: staging-api-key
