apiVersion: v1
kind: Service
metadata:
  labels:
    role: ingestion
  name: mongo-service
  namespace: integration-environment
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongo
  sessionAffinity: None
  type: ClusterIP
