apiVersion: v1
kind: Service
metadata:
  labels:
    role: submission
  name: rabbit-service
  namespace: integration-environment
spec:
  ports:
    - name: service
      port: 5672
      protocol: TCP
      targetPort: 5672
    - port: 15672
      protocol: TCP
      targetPort: 15672
      name: manager
  selector:
    app: rabbit
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
