---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingest-staging-manager
  namespace: staging-environment
  labels:
    role: ingestion
spec:
  replicas: 1
  strategy:
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        app: ingest-staging-manager
    spec:
      containers:
         - name: ingest-staging-manager
           imagePullPolicy: Always
           image: quay.io/humancellatlas/ingest-staging-manager:v0.1.0.rc
           env:
             - name: INGEST_API
               value: http://api.ingest.staging.data.humancellatlas.org:80
             - name: RABBIT_URL
               value: amqp://${RABBIT_SERVICE_SERVICE_HOST}:${RABBIT_SERVICE_SERVICE_PORT_SERVICE}
             - name: STAGING_API
               value: https://upload.staging.data.humancellatlas.org
             - name: INGEST_API_KEY
               valueFrom:
                 secretKeyRef:
                   name: api-keys
                   key: staging-api-key
