---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
  namespace: staging-environment
  labels:
    role: ingestion
spec:
  replicas: 1 
  template: 
    metadata:
      labels:
        app: mongo
    spec:
      containers:
         - name: mongo
           image: mongo:3.4.3
           ports:
             - containerPort: 27017
