---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: ingestion
  name: ingest-demo-service
  namespace: staging-environment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: ingest-demo
  sessionAffinity: None
  type: LoadBalancer
