---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: ingestion
  name: ingest-core-service
  namespace: staging-environment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ingest-core
  sessionAffinity: None
  type: LoadBalancer
