---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingest-exporter
  labels:
    role: ingestion
spec:
  replicas: 1
  strategy: 
    type: "RollingUpdate"
  template: 
    metadata:
      labels:
        app: ingest-exporter
    spec:
      containers:
         - name: ingest-exporter
           image: ingest-exporter:local
           env:
             - name: INGEST_API
               value: http://${INGEST_CORE_SERVICE_SERVICE_HOST}:${INGEST_CORE_SERVICE_SERVICE_PORT}
             - name: RABBIT_URL
               value: amqp://${RABBIT_SERVICE_SERVICE_HOST}:${RABBIT_SERVICE_SERVICE_PORT_SERVICE}
