---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingest-demo
  labels:
    role: ingestion
spec:
  replicas: 1
  strategy: 
    type: "RollingUpdate"
  template: 
    metadata:
      labels:
        app: ingest-demo
    spec:
      containers:
         - name: ingest-demo
           image: ingest-demo:local
           env:
             - name: INGEST_API
               value: http://${INGEST_CORE_SERVICE_SERVICE_HOST}:${INGEST_CORE_SERVICE_SERVICE_PORT}
           ports:
             - containerPort: 5000
